apiVersion: 1

datasources:
  # VictoriaMetrics - Metrics
  - name: VictoriaMetrics
    type: prometheus
    access: proxy
    url: http://victoriametrics:8428
    isDefault: true
    editable: false
    jsonData:
      timeInterval: "10s"
      httpMethod: POST

  # OpenObserve - Logs
  - name: OpenObserve
    type: elasticsearch
    access: proxy
    url: http://openobserve:5080/api/default
    basicAuth: true
    basicAuthUser: ${OO_ROOT_EMAIL:-admin@sidra.local}
    editable: false
    jsonData:
      index: "logs"
      timeField: "_timestamp"
      esVersion: "7.10.0"
    secureJsonData:
      basicAuthPassword: ${OO_ROOT_PASSWORD:-SidraMonitor2024!}
